### 5.1. Tela de Login

url: https://www.plantuml.com/plantuml/png/pLIzRjim4Dxr50TDjWCtheiiMc8Z2H04S1BOG1R3muMwsWGeqYKf3wtp8bqx50ZGgO-W5yjHbWmvCOAuQO5oEXxlZjyFfO7pQBr3vQDl4S27AzIa4E8peqbuX97HqXih4Rem5EISYRaib0B45nbA1IQ74NfR_1AvmhWycSB-DTlqJKWltbJPWWljBLfeLnUwBpa9oi7b22vCETsCYQ-B7mOyPI0mHUUjEONfcEQIG-ewceMoX-WX6f1EIxRHu03crIG6ClHo9LDCoJLqE9TEoAMI6fCOujkRcmhKg7XqtFkPRF6eXGodKvWGmxotvhZVwv_KYbmQYw4KbVmQ29IL7tlryJavOMNnCv3aqmQAv7KPNqhwBog3JIl9wenPGL_yjj90cxDdg0LdDlQzH_rwgeCbMeJXqfeLbd8qNBZ3EIRGwR3-dGwiwn49JAzDHf2QEZEhx6dElMLafFrMqAFkWUkeREDRsVE0OiVc4a_fSH9StLdhgh7XCKE-8yiPZsf1RhPV-xgnLUbXIyt7jDsysdOel_KpViEvSNuFkvF_WTqVkhVp8ZRNfXorYk_AouoZJv2H8zV-Eu_aAbUBwZUmrQ_VutZYqUUygI6yXrNpiti2

**Código PlantUML:**
```plantuml
@startsalt
{
  .Janela "Conecta Monitoria - Acesso"
  {
    "Email ou Matrícula"
    [                       ]
    "Senha"
    [                       ]
    ( Entrar )
    "Esqueceu sua senha?"
    "Não tem cadastro? [Registre-se]"
  }
}
@endsalt
```

---

### 5.2. Painel do Aluno

url: https://www.plantuml.com/plantuml/dpng/jT2nIeCn50NWFKzno6G7jHPSd2gj84Afr54wNFDVvK9CvERIGUdJE0XTVOIyc8a_ukXandE-0-7EYv5QeMZkpG4dDvGu4lmY9mv6MEKabbK8nzZmanHJKboQx6IWWOjtG1y2VYabo4kKH1SU_dQzzcE-geVIje-izP22zFOUTspy_A3vT3QTdMCxokkir2b5UQM1ohSyc_xKIov1fNxKzupM_lwYmIuQ_ljj_qqUuIhjX1GRZcJrKoLZqj85fT0InQInlTkxEQUXN_mB

```plantuml
@startsalt
{
  .Janela "Conecta Monitoria - Registrar Atividades"
  {
    "Disciplina:" "POO"
    "Mês Referência:" [ Setembro/2025 ]
    "Horas Realizadas:" [ 10 ]
    "Descrição das Atividades:"
    [                                   ]
    [                                   ]
    [                                   ]
    ( Enviar Relatório ) ( Cancelar )
  }
}
@endsalt
```

## Painel do Professor - Aprovação de Relatórios

url: https://www.plantuml.com/plantuml/dpng/nLAnJW914EtlAoPNmH4KCJHK42qCYK8WeJ4K8pU1I_PsoSvWu_4ZjXOcjdx2_PXp7ATYY0d1n5UztScRVMzsUYpeXT58y1G0d0tGaa48hvobkI3SEfk8ymb24yPQaVpT9uvXXHwXl_Bk4VFN_CM5AjO6Yd2A2-n258s6moY2h6hHXVixbnB4hhgPXQNWUzyHsPYi47VBOgDv91g5h7WrV-F2nOI4qWVlpjkjTcVhvyPvrD952_QGxOJNn7EVR4EfvIbvlH4qI-8PL3WehEtcuQ6kV4oVXrzbn-RBVkJhBnpBWNITVqvtmk_jRqJvRAoibZyRIL9bbv0I4zV_Paa6QxCi9_WrltPB-KHGrdgeB9oIQXDiWXxPcD781m00

```plantuml
@startsalt
{
  .Janela "Conecta Monitoria - Relatórios para Aprovação"
  {
    "Vaga: **POO** | Monitor: [Nome do Monitor]"
    "Relatórios Pendentes:"
    +------------------------------------------------+
    | Mês: **Setembro/2025** | Horas: 10              |
    | Descrição: [Ver Detalhes]                      |
    | ( Aprovar ) ( Reprovar )                       |
    |------------------------------------------------|
    | Mês: **Agosto/2025** | Horas: 15              |
    | Descrição: [Ver Detalhes]                      |
    | ( Aprovar ) ( Reprovar )                       |
    +------------------------------------------------+
    "Relatórios Aprovados (Últimos 3 meses):"
    +------------------------------------------------+
    | Mês: Julho/2025 | Horas: 20 | Status: Aprovado |
    +------------------------------------------------+
  }
}
@endsalt
