# Generated by Django 5.2.7 on 2025-10-30 18:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('curso', models.CharField(max_length=50)),
                ('periodo', models.IntegerField()),
                ('cra', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='AtividadeMonitoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_registro', models.DateField()),
                ('horas_realizadas', models.PositiveIntegerField()),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado')], default='PENDENTE', max_length=20)),
            ],
            options={
                'verbose_name': 'Atividade de Monitoria',
                'verbose_name_plural': 'Atividades de Monitoria',
            },
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_candidatura', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUBMETIDA', 'Submetida'), ('EM_AVALIACAO', 'Em Avaliação'), ('APROVADA', 'Aprovada'), ('REPROVADA', 'Reprovada'), ('DESISTENTE', 'Desistente')], default='SUBMETIDA', max_length=20)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='myapp.aluno')),
            ],
            options={
                'verbose_name': 'Candidatura',
                'verbose_name_plural': 'Candidaturas',
            },
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('area_responsavel', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Coordenador',
                'verbose_name_plural': 'Coordenadores',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('departamento', models.CharField(max_length=50)),
                ('siape', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('requisitos', models.TextField()),
                ('num_vagas', models.IntegerField(default=1)),
                ('data_abertura', models.DateField()),
                ('data_encerramento', models.DateField()),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PENDENTE', 'Pendente de Aprovação'), ('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('CONCLUIDA', 'Concluída')], default='RASCUNHO', max_length=20)),
                ('coordenador_homologador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vagas_homologadas', to='myapp.coordenador')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vagas', to='myapp.disciplina')),
                ('professor_publicador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vagas_publicadas', to='myapp.professor')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
            },
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.AddField(
            model_name='atividademonitoria',
            name='candidatura_aprovada',
            field=models.ForeignKey(limit_choices_to={'status': 'APROVADA'}, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='myapp.candidatura'),
        ),
        migrations.AddField(
            model_name='atividademonitoria',
            name='professor_revisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_revisadas', to='myapp.professor'),
        ),
        migrations.AddField(
            model_name='candidatura',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='myapp.vaga'),
        ),
        migrations.AlterUniqueTogether(
            name='candidatura',
            unique_together={('aluno', 'vaga')},
        ),
    ]
